version: '3.8'
services:
  mkdocs:
    build:
      context: .
      dockerfile: Dockerfile
    entrypoint:
      - /bin/ash
      - -c
      - python3 -m mkdocs serve --livereload -a 0.0.0.0:8000
    ports:
      - '8000:8000'
    restart: always
    tty: true
    volumes:
      - .:/opt/:delegated
