site_name: kata_dev
theme:
  name: material
  language: en
  custom_dir: overrides
  font:
    text: IBM Plex Sans
    code: Roboto Mono
  favicon: images/cat.jpg
  logo: images/cat.jpg
  features:
    - content.code.annotate
    # 検索
    - search.suggest
    - search.highlight
    - search.share

    # ナビゲーション
    - navigation.instant     ## mkdocs for MaterialのSPA対応
    # - navigation.tabs        ## トップレベル項目を画面上部メニューにタブ表示
    - navigation.tracking
    - navigation.sections  ## 項目のセクション表示
    - navigation.expand    ## 初期表示で全てのページ展開を有効化
    - navigation.top       ## ページTOP遷移ボタンを有効化
    - toc.integrate        ## 画面左右のメニューを統合
    - toc.follow
    - header.autohide
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default  ## カラースキーム設定(default:ライトモード、slate:ダークモード)
      primary: cyan
      accent: amber
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      accent: teal
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
plugins:
  - search:
      lang:
        - ja
        - en
      # 空白・ハイフン・ドット・アンスコを区切り文字としてインデックスする
      separator: '[\s\-\.\_]+'
  - tags
  - git-revision-date-localized:
      locale: ja
      timezone: Asia/Tokyo
      type: datetime
      enable_creation_date: true

markdown_extensions:
  # Python Markdown
  - meta
  - admonition # アラート修飾の設定
  - tables
  - attr_list
  - md_in_html
  - footnotes
  - codehilite
  - toc:
      permalink: true

  # Python Markdown Extensions
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.caret
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.tilde
  - pymdownx.details # コンテンツの折りたたみ設定

extra_javascript:
  - https://unpkg.com/tablesort@5.3.0/dist/tablesort.min.js
  # - javascripts/tablesort.js

extra:
  social:
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/kata_dev
    - icon: fontawesome/brands/github
      link: https://github.com/kynefuk
  generator: false
  analytics:
    provider: google
    property: G-PQR25NVWJ7
copyright: Copyright © 2022 kata_dev